export const activityTypes = {
  CREATE_EVENT: 'CREATE_EVENT',
  UPDATE_TITLE: 'UPDATE_TITLE',
  EVENT_COMPLETE: 'EVENT_COMPLETE',
  EVENT_RESET: 'EVENT_RESET',
  UPDATE_DATE: 'UPDATE_DATE',
  COMMENT: 'COMMENT'
};
